version: '3'

networks:
    node-network:
        driver: bridge

services:
    server:
        build: ./server
        volumes:
            - ./server:/user/wwww
            - /user/wwww/node_modules
        ports:
            - "3000:3000"
        restart: unless-stopped
        networks:
            - node-network
    client:
        build: ./client
        volumes:
            - ./client::/user/wwww
            - /user/wwww/node_modules
        ports:
        - "8080:8080"
        restart: unless-stopped
        networks:
            - node-network
